// Code generated by "stringer -type=Preference"; DO NOT EDIT.

package preferences

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[JumpToEmptySquare-0]
	_ = x[SwapCursorOnGridWrap-1]
	_ = x[SwapCursorOnDirectionChange-2]
	_ = x[WrapAtEndOfGrid-3]
	_ = x[WrapOnArrowNavigation-4]
}

const _Preference_name = "JumpToEmptySquareSwapCursorOnGridWrapSwapCursorOnDirectionChangeWrapAtEndOfGridWrapOnArrowNavigation"

var _Preference_index = [...]uint8{0, 17, 37, 64, 79, 100}

func (i Preference) String() string {
	if i < 0 || i >= Preference(len(_Preference_index)-1) {
		return "Preference(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Preference_name[_Preference_index[i]:_Preference_index[i+1]]
}
